version: "3.4"

services:
    app:
        container_name: golang_container
        environment:
          - POSTGRES_URL=${POSTGRES_URL}
        tty: true
        build: .
        ports:
          - 8080:8080
        restart: on-failure
        volumes:
          - .:/app
        depends_on:
          - postgresdb
        networks:
          - learning
    pgAdmin:
        restart: always
        image: dpage/pgadmin4
        ports:
          - "8000:80"
        environment:
          PGADMIN_DEFAULT_EMAIL: admin@example.com
          PGADMIN_DEFAULT_PASSWORD: 1234
        volumes:
          - pgadmin:/var/lib/pgadmin
        networks:
          - learning
    postgresdb:
        restart: always
        image: postgres
        container_name: "postgres_container"
        ports:
          - "5432:5432"
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: db_golang_api
        volumes:
          - pgvol:/var/lib/postgresql/data
          - ./db_golang_api.sql:/docker-entrypoint-initdb.d/data.sql
        networks:
          - learning

volumes:
  pgvol:
  pgadmin:

# # Networks to be created to facilitate communication between containers
networks:
  learning:
    driver: bridge